spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/app__2022_10_05___test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/app__2022_10_05___test?serverTimezone=UTC
    username: appuser1
    password: app1234
  jpa:
    hibernate:
      ddl-auto: create